services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api_rembg
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
#    environment:
#      - FLASK_ENV=development
#    deploy:
#      resources:
#        limits:
#          cpus: "0.5" # Limitar al 50% de un nucleo
#          memory: "512M" # limitar a 512Mb de ram
#    networks:
#      - api_rembg_network
#networks:
#  api_rembg_network:
#    driver: bridge